apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: recommendationservice
          image: 'softtekcoeapisms/recommendationservice:1.0'
          ports:
            - containerPort: 80
          env:
          - name: ProductCatalogServiceURL
            value: http://productcatalogservice/api/
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    name: recommendationservice
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: recommendationservice
  type: ClusterIP